/*-----------------------------------------------------------------------------
 * TITLE: OEM_TIMER.C
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *---------------------------------------------------------------------------*/

#include <CORE_INCLUDE.H>
#include <OEM_INCLUDE.H>


//	   PS2	PS1	PS0 	WDIDLE   ¡§C  	SWRST 	WDTOVF 	WDTEN
//Bit    7		6 	5 	 4 	    		3 	  2 	 		1 	   0

//PS2
//PS1
//PS0
//			Prescaler bits for the watchdog timer (WDT). When all three bits are cleared to 0, the watchdog timer has a nominal
//			period of 16K clock cycles. When all three bits are set to 1, the nominal period is 2048K clock cycles.

//WDIDLE 	Disable/enable the Watchdog Timer in IDLE mode.
//          When WDIDLE = 0, WDT continues to count in IDLE mode. When
//		         WDIDLE = 1, WDT freezes while the device is in IDLE mode.
//SWRST 	Software Reset Flag. Set when a software reset is generated by writing the sequence 5AH/A5H to WDTRST. Also set
//          when an incorrect sequence is written to WDTRST. Must be cleared by software.
//WDTOVF    Watchdog Overflow Flag. Set when a WDT rest is generated by the WDT timer overflow. Also set when an incorrect
//          sequence is written to WDTRST. Must be cleared by software.
//WDTEN     Watchdog Enable Flag. This bit is READ-ONLY and reflects the status of the WDT (whether it is running or not). The
//          WDT is disabled after any reset and must be re-enabled by writing 1EH/E1H to WDTRST


void ExtWDTInit(void)
{
    #if	WATCHDOG
	 ETPSR=0x00;			// SELECT 32.768Khz
	 ETCNTLHR=0x80;	   	// SET EXTERNAL TIMERR = 1sec
	 ETCNTLLR=0x00;		// SET EXTERNAL TIMERR = 1sec 
	 //EWDCNTLR=WATCHDOG_COUNTER;	// SET WATCHDOG TIMER = WATCHDOG_COUNTER ("DEFINE.H")
	 ETWCFG=0x20;		   	// LOCK WATCHDOG REGISTER
	 ETWCTRL = 0x10;        //EWDCMS  External WDT stop count mode select   1: External WDT can be stopped by setting EWDSCEN bit,   0: External WDT cannot be stopped
	 ETWCTRL = 0x30;        //External WDT stop count enable  1: stop   0:otherwise.	 
    #endif // WATCHDOG
}

//----------------------------------------------------------------------------
// Enable internal watch dog and waiting EC reset                 
//----------------------------------------------------------------------------
void InternalWDTNow(void)
{
	WDTCON|=0x01;   // WDTRST = 1 Reset watch dog timer.
	WDTCON|=0x02;   // WDTEN  = 1 Enable watch dog.     
	while(1);       // Wait for watch dog time-out      
}

//----------------------------------------------------------------------------
// Enable internal watch dog
//----------------------------------------------------------------------------
void EnableInternalWDT(void)
{
	CKCON |= 0xC0;		    // set 26 bit counter
	WDTRST = 1;				// reset internal watch dog
	WDTEB = 1;				// enable internal watch dog		
}

//----------------------------------------------------------------------------
// Disable internal watch dog
//----------------------------------------------------------------------------
void DisableInternalWDT(void)
{
	WDTEB = 0;				// Disable internal watch dog
}

//----------------------------------------------------------------------------
// Disable internal watch dog
//----------------------------------------------------------------------------
void ResetInternalWDT(void)
{
	WDTRST = 1;				// Reset internal watch dog counter
}