/*-----------------------------------------------------------------------------
 * TITLE: OEM_HOSTIF.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/

#ifndef OEM_HOSTIF_H
#define OEM_HOSTIF_H

extern void InitSio(void);
extern void InitSysMemory2ECRam(void);

#endif