/*-----------------------------------------------------------------------------
 * TITLE: OEM_INCLUDE.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/

#ifndef OEM_INCLUDE_H
#define OEM_INCLUDE_H

//----------------------------------------------------------------------------
// OEM Bank0
//----------------------------------------------------------------------------
#include <OEM_GPIO.H>
#include <OEM_Project.H>
#include <OEM_INIT.H>
#include <OEM_MAIN.H>
#include <OEM_LED.H>
#include <OEM_FAN.H>
#include <OEM_BATTERY.H>
#include <OEM_MEMORY.H>
#include <OEM_POWER.H>
#include <OEM_EVENT.H>
#include <OEM_SMBUS.H>
#include <OEM_SCANTABS.H>
#include <OEM_ADC.H>
#include <OEM_MMB.H>
#include <OEM_ACPI.H>
#include <OEM_CIR.H>
#include <OEM_FLASH.H>
#include <OEM_HOSTIF.H>
#include <OEM_6064.H>
#include <OEM_MailBox.H>
#include <OEM_Ver.H>
#include <OEM_LCD.H>
#include <OEM_PORT686C.H>
#include <OEM_PECI.H>
#include <OEM_PM3.H>
#include <OEM_SPI.H>
#include <OEM_IRQ.H>
#include <OEM_PM2.H>
#include <OEM_PS2.H>
#include <OEM_SPI.H>
#include <OEM_LPC.H>
#include <OEM_Timer.H>
#include <OEM_HSPI.H>
#include <OEM_ASM.H>
#include <OEM_Debug.H>
#include <Oem_Uart.H>
#include <OEM_HEAT.H>
#include <math.h>
//----------------------------------------------------------------------------
// OEM Bank1
//----------------------------------------------------------------------------
#include <OEM_BANK1_Func.H>
#include <SHA1.H> 
#include <STDLIB.H> 	//for use rand() to creat random data for sha1
//----------------------------------------------------------------------------
// OEM Bank2
//----------------------------------------------------------------------------
#include <OEM_BANK2_Func.H>

//----------------------------------------------------------------------------
// OEM Ban3
//----------------------------------------------------------------------------
#include <OEM_BANK3_Func.H>

#endif